export const TEMP_DATA = "TEMP_DATA";
export const TEMP_ERROR = "TEMP_ERROR";
export const TEMP_START_LOADING = "TEMP_START_LOADING";
export const TEMP_STOP_LOADING = "TEMP_STOP_LOADING";


export const UPDATE_TEMP_DATA = "TEMP_DATA";
export const UPDATE_TEMP_ERROR = "TEMP_ERROR";
export const UPDATE_TEMP_START_LOADING = "TEMP_START_LOADING";
export const UPDATE_TEMP_STOP_LOADING = "TEMP_STOP_LOADING";
